//IMPORTANT: This file is automatically generated by @rewindbitcoin/i18n
//DO NOT EDIT it. Usage: npx i18n_rewbtc [src] #to re-generate it.
//More info: @rewindbitcoin/i18n README.md

export const locales = ['en', 'es'];
export type Locale = "en-US" | "es-ES" | "es" | "en";
import i18n, { i18n as I18nInstance } from "i18next";
import { initReactI18next } from "react-i18next";

import en from "./en";
import es from "./es";

const resources = {
  en: { translation: en },
  es: { translation: es }
};

i18n.use(initReactI18next).init({
  resources,
  fallbackLng: "en", // Default language

  interpolation: {
    escapeValue: false,
  },
});

export const i18nInstances: Record<Locale, I18nInstance> = locales.reduce(
  (acc, locale) => {
    acc[locale as Locale] = i18n.cloneInstance({ lng: locale }); // Asserting locale as Locale
    return acc;
  },
  {} as Record<Locale, I18nInstance>
);

export async function initI18n(locale: Locale) {
  await i18n.changeLanguage(locale);
}

export { i18n };
