//uses react-native-dotenv from bable.config.js and @rewindbitcoin/env
import {
  PUBLIC_PROTOCOL,
  PUBLIC_API_SERVER_NAME,
  PUBLIC_MAINNET_SERVICE_ADDRESS_LOCATION,
  PUBLIC_TESTNET_SERVICE_ADDRESS_LOCATION,
  PUBLIC_PLAYNET_SERVICE_ADDRESS_LOCATION,
  LOCAL_PROTOCOL,
  LOCAL_HOST_NAME,
  LOCAL_REGTEST_SERVICE_ADDRESS_PORT,
  PUBLIC_MAINNET_VAULTS_WRITER_LOCATION,
  PUBLIC_TESTNET_VAULTS_WRITER_LOCATION,
  PUBLIC_PLAYNET_VAULTS_WRITER_LOCATION,
  LOCAL_REGTEST_VAULTS_WRITER_PORT,
  LOCAL_REGTEST_VAULTS_READER_PORT,
  LOCAL_REGTEST_ESPLORA_API_PORT,
  PUBLIC_BTC_RATES_LOCATION,
  PUBLIC_API_SECONDARY_SERVER_NAME,
  PUBLIC_MAINNET_VAULTS_READER_LOCATION,
  PUBLIC_TESTNET_VAULTS_READER_LOCATION,
  PUBLIC_PLAYNET_VAULTS_READER_LOCATION,
  PUBLIC_PLAYNET_SERVER_NAME,
  PUBLIC_PLAYNET_WEB_LOCATION,
  LOCAL_REGTEST_WEB_PORT,
  PUBLIC_PLAYNET_ESPLORA_API_LOCATION,
  PUBLIC_PLAYNET_BLOCK_EXPLORER_LOCATION,
  LOCAL_REGTEST_BLOCK_EXPLORER_PORT
  // @ts-expect-error @env is defined in bable.config.js
} from '@env';

export const subUnits = ['btc', 'bit', 'sat', 'mbit'] as const;
export type SubUnit = (typeof subUnits)[number];
export type Currency = 'USD' | 'EUR' | 'GBP'; //Keep in sync with thunderDenServices/btcRates
import type { Locale } from '../../i18n-locales/init';
export const SETTINGS_GLOBAL_STORAGE = 'SETTINGS_GLOBAL_STORAGE';

export interface Settings {
  GAP_LIMIT: number;
  SERVICE_FEE_RATE: number;
  MIN_FEE_RATE: number;
  MIN_LOCK_BLOCKS: number;
  MAX_LOCK_BLOCKS: number;
  INITIAL_LOCK_BLOCKS: number;
  SAMPLES: number;
  PRESIGNED_FEE_RATE_CEILING: number;
  INITIAL_CONFIRMATION_TIME: number;
  MIN_RECOVERABLE_RATIO: number;
  SUB_UNIT: SubUnit;
  FIAT_MODE: boolean;
  LOCALE: Locale;
  CURRENCY: Currency;
  BTC_FIAT_REFRESH_INTERVAL_MS: number;
  BLOCKCHAIN_DATA_REFRESH_INTERVAL_MS: number;
  WALLETS_DATA_VERSION: string;

  MAINNET_SERVICE_ADDRESS_API: string;
  TESTNET_SERVICE_ADDRESS_API: string;
  PLAYNET_SERVICE_ADDRESS_API: string;
  REGTEST_SERVICE_ADDRESS_API: string;

  MAINNET_VAULTS_API: string;
  TESTNET_VAULTS_API: string;
  PLAYNET_VAULTS_API: string;
  REGTEST_VAULTS_API: string;

  BTC_RATES_API: string;

  MAINNET_VAULTS_SECONDARY_API: string;
  TESTNET_VAULTS_SECONDARY_API: string;
  PLAYNET_VAULTS_SECONDARY_API: string;
  REGTEST_VAULTS_SECONDARY_API: string;

  MAINNET_ESPLORA_API: string;
  TESTNET_ESPLORA_API: string;
  PLAYNET_ESPLORA_API: string;
  REGTEST_ESPLORA_API: string;

  PLAYNET_WEB_SERVER: string;
  REGTEST_WEB_SERVER: string;

  MAINNET_BLOCK_EXPLORER: string;
  TESTNET_BLOCK_EXPLORER: string;
  PLAYNET_BLOCK_EXPLORER: string;
  REGTEST_BLOCK_EXPLORER: string;
}

// Default values for the context
export const defaultSettings: Settings = {
  GAP_LIMIT: 20,
  SERVICE_FEE_RATE: 0.0004,
  MIN_FEE_RATE: 1,
  MIN_LOCK_BLOCKS: 1,
  MAX_LOCK_BLOCKS: 3 * 30 * 24 * 6,
  INITIAL_LOCK_BLOCKS: 7 * 24 * 6,
  //TODO: set it to larger values in production
  SAMPLES: 60, //This corresponds to (PRESIGNED_FEE_RATE_CEILING ^ (1/SAMPLES) - 1) * 100 / 2 = 8% expected increase in fees wrt to ideal case, which is perfectly fine
  //TODO: this should be 5 * 1000; I set it to 10 for testnet tests
  //PRESIGNED_FEE_RATE_CEILING: 5 * 1000, //22-dec-2017 fee rates were 1000. TODO: Set this to 5000 which is 5x 22-dec-2017
  //https://twitter.com/KLoaec/status/1733880025017978914
  //PRESIGNED_FEE_RATE_CEILING: 2,
  PRESIGNED_FEE_RATE_CEILING: 10000, //TODO should be 10000
  // 2 hours
  INITIAL_CONFIRMATION_TIME: 2 * 60 * 60,
  MIN_RECOVERABLE_RATIO: 1 / 50, //TODO should it be 2/3?
  SUB_UNIT: 'btc',
  FIAT_MODE: false, //whether the user prefers using fiat than SUB_UNIT
  LOCALE: 'en-US',
  CURRENCY: 'USD',
  BTC_FIAT_REFRESH_INTERVAL_MS: 600000, //10 minutes
  BLOCKCHAIN_DATA_REFRESH_INTERVAL_MS: 60000, // 1 minute
  WALLETS_DATA_VERSION: '1.0.0', //This does not define the version of the App, but keeps track of the changes in the signature of the Wallet

  MAINNET_SERVICE_ADDRESS_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_MAINNET_SERVICE_ADDRESS_LOCATION}`,
  TESTNET_SERVICE_ADDRESS_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_TESTNET_SERVICE_ADDRESS_LOCATION}`,
  PLAYNET_SERVICE_ADDRESS_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_PLAYNET_SERVICE_ADDRESS_LOCATION}`,
  REGTEST_SERVICE_ADDRESS_API: `${LOCAL_PROTOCOL}://${LOCAL_HOST_NAME}:${LOCAL_REGTEST_SERVICE_ADDRESS_PORT}`,

  MAINNET_VAULTS_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_MAINNET_VAULTS_WRITER_LOCATION}`,
  TESTNET_VAULTS_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_TESTNET_VAULTS_WRITER_LOCATION}`,
  PLAYNET_VAULTS_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_PLAYNET_VAULTS_WRITER_LOCATION}`,
  REGTEST_VAULTS_API: `${LOCAL_PROTOCOL}://${LOCAL_HOST_NAME}:${LOCAL_REGTEST_VAULTS_WRITER_PORT}`,

  BTC_RATES_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SERVER_NAME}${PUBLIC_BTC_RATES_LOCATION}`,

  MAINNET_VAULTS_SECONDARY_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SECONDARY_SERVER_NAME}${PUBLIC_MAINNET_VAULTS_READER_LOCATION}`,
  TESTNET_VAULTS_SECONDARY_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SECONDARY_SERVER_NAME}${PUBLIC_TESTNET_VAULTS_READER_LOCATION}`,
  PLAYNET_VAULTS_SECONDARY_API: `${PUBLIC_PROTOCOL}://${PUBLIC_API_SECONDARY_SERVER_NAME}${PUBLIC_PLAYNET_VAULTS_READER_LOCATION}`,
  REGTEST_VAULTS_SECONDARY_API: `${LOCAL_PROTOCOL}://${LOCAL_HOST_NAME}:${LOCAL_REGTEST_VAULTS_READER_PORT}`,

  MAINNET_ESPLORA_API: 'https://blockstream.info/api',
  TESTNET_ESPLORA_API: 'https://blockstream.info/testnet/api',
  PLAYNET_ESPLORA_API: `${PUBLIC_PROTOCOL}://${PUBLIC_PLAYNET_SERVER_NAME}${PUBLIC_PLAYNET_ESPLORA_API_LOCATION}`,
  REGTEST_ESPLORA_API: `${LOCAL_PROTOCOL}://${LOCAL_HOST_NAME}:${LOCAL_REGTEST_ESPLORA_API_PORT}`,

  MAINNET_BLOCK_EXPLORER: 'https://blockstream.info/',
  TESTNET_BLOCK_EXPLORER: 'https://blockstream.info/testnet/',
  PLAYNET_BLOCK_EXPLORER: `${PUBLIC_PROTOCOL}://${PUBLIC_PLAYNET_SERVER_NAME}${PUBLIC_PLAYNET_BLOCK_EXPLORER_LOCATION}`,
  REGTEST_BLOCK_EXPLORER: `${LOCAL_PROTOCOL}://${LOCAL_HOST_NAME}:${LOCAL_REGTEST_BLOCK_EXPLORER_PORT}`,

  //PlayNet Web Server (the faucet entry point + web server with service description)
  PLAYNET_WEB_SERVER: `${PUBLIC_PROTOCOL}://${PUBLIC_PLAYNET_SERVER_NAME}${PUBLIC_PLAYNET_WEB_LOCATION}`,
  REGTEST_WEB_SERVER: `${LOCAL_PROTOCOL}://${LOCAL_HOST_NAME}:${LOCAL_REGTEST_WEB_PORT}`
};
